#### general settings
name: ir-sde
use_tb_logger: true
model: denoising
distortion: derain
gpu_ids: [0]
wandb_proj: 'pre-cond'
wandb_run: '10-nerf-preRLSID404550-nf64depth4'

sde:
  max_sigma: 10
  T: 10
  schedule: cosine # linear, constant
  eps: 0.005

degradation: # for some synthetic dataset that only have GTs
  # for denoising
  sigma: 25
  noise_type: G # Gaussian noise: G

  # for super-resolution
  scale: 4 #2 x quan split dataset
  

#### datasets
datasets:
  train:
    name: Train_Dataset
    mode: LQGT
    dataroot_GT: /home/apinyol/Gits/proves/repos_ref/datasets/neRF2/Train/GT
    dataroot_LQ: /home/apinyol/Gits/proves/repos_ref/datasets/neRF2/Train/LQ

    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 4 #4*4 x quan split dataset
    GT_size: 256
    LR_size: 256
    use_flip: true
    use_rot: true
    color: RGB
    resize: true
    mida_resize: 128
    tasca: "llum2" #roig per fer transformació canals

  val:
    name: Val_Dataset
    mode: LQGT
    dataroot_GT: /home/apinyol/Gits/proves/repos_ref/datasets/neRF2/Test/GT
    dataroot_LQ: /home/apinyol/Gits/proves/repos_ref/datasets/neRF2/Test/LQ

    #abril:
    GT_size: 256
    LR_size: 256
    n_workers: 4  
    batch_size: 4 

    resize: true
    mida_resize: 128
    tasca: "llum2" #roig per fer transformació canals

  lighting:
    name: Lighting
    mode: ~
    dataroot_GT: path
    

#### network structures
network_G:
  which_model_G: ConditionalUNet
  setting:
    in_nc: 3
    out_nc: 3
    nf: 64
    depth: 4

#### path
path:
  pretrain_model_G: /home/apinyol/Gits/proves/repos_ref/IR-SDE-Abril/experiments/deraining/ir-sde/10-rlsid404550-pret/deraining-nf64depth4-303913/models/30000_G.pth
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  optimizer: Adam # Adam, AdamW, Lion
  lr_G: !!float 1e-4
  lr_scheme: TrueCosineAnnealingLR
  beta1: 0.9
  beta2: 0.99
  niter: 50000
  warmup_iter: -1  # no warm up
  lr_steps: [200000, 400000, 600000]
  lr_gamma: 0.5
  eta_min: !!float 1e-7

  # criterion
  is_weighted: False
  loss_type: l1
  weight: 1.0

  manual_seed: 0
  val_freq: 3000

#### logger
logger:
  print_freq: 1
  save_checkpoint_freq: 10000