#### general settings
name: refusion
use_tb_logger: true
model: denoising
distortion: derain
gpu_ids: [1]
wandb_proj: 'proves'
wandb_run: 'patata'
tasca: "-" #roig per fer transformació canals

sde:
  max_sigma: 50
  T: 100
  schedule: cosine # linear, cosine
  eps: 0.005

degradation: # for some synthetic dataset that only have GTs
  # for denoising
  sigma: 25
  noise_type: G # Gaussian noise: G

  # for super-resolution
  scale: 2
  
#### datasets
datasets:
  train:
    optimizer: Lion # Adam, AdamW, Lion
    name: Train_Dataset
    mode: LQGT
    dataroot_GT: /home/apinyol/Gits/proves/repos_ref/datasets/neRF2/Train/GT
    dataroot_LQ: /home/apinyol/Gits/proves/repos_ref/datasets/neRF2/Train/LQ

    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 16
    GT_size: 128
    LR_size: 128
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: Val_Dataset
    mode: LQGT
    dataroot_GT: /home/apinyol/Gits/proves/repos_ref/datasets/proves_nerf/Mediana
    dataroot_LQ: /home/apinyol/Gits/proves/repos_ref/datasets/proves_nerf/Mediana

    #abril:
    GT_size: 128
    LR_size: 128
    n_workers: 4  
    batch_size: 4 


#### network structures
network_G:
  which_model_G: ConditionalNAFNet
  setting:
    width: 64
    enc_blk_nums: [1, 1, 1, 28]
    middle_blk_num: 1
    dec_blk_nums: [1, 1, 1, 1]

#### path
path:
  pretrain_model_G: /home/apinyol/Gits/proves/repos_ref/pretrained_models/pretrained-deshadow-reffusion/reffusion-deshadow.pth
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  optimizer: Lion # Adam, AdamW, Lion
  lr_G: !!float 4e-5
  lr_scheme: TrueCosineAnnealingLR
  beta1: 0.9
  beta2: 0.99
  niter: 50000
  warmup_iter: -1  # no warm up
  lr_steps: [200000, 400000, 600000]
  lr_gamma: 0.5
  eta_min: !!float 1e-7

  # criterion
  is_weighted: False
  loss_type: l1
  weight: 1.0

  manual_seed: 0
  val_freq: 1

#### logger
logger:
  print_freq: 1
  save_checkpoint_freq: 5000
